/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CenterRouteRouteImport } from './routes/center/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CenterIndexRouteImport } from './routes/center/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CenterStudentsRouteImport } from './routes/center/students'
import { Route as CenterSettingsRouteImport } from './routes/center/settings'
import { Route as CenterMarksEntryRouteImport } from './routes/center/marks-entry'
import { Route as CenterExamFormsRouteImport } from './routes/center/exam-forms'
import { Route as CenterEnrollRouteImport } from './routes/center/enroll'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminExamsRouteImport } from './routes/admin/exams'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminCoordinatorsRouteImport } from './routes/admin/coordinators'
import { Route as AdminCentersRouteImport } from './routes/admin/centers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterRouteRoute = CenterRouteRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterIndexRoute = CenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CenterRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CenterStudentsRoute = CenterStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CenterRouteRoute,
} as any)
const CenterSettingsRoute = CenterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CenterRouteRoute,
} as any)
const CenterMarksEntryRoute = CenterMarksEntryRouteImport.update({
  id: '/marks-entry',
  path: '/marks-entry',
  getParentRoute: () => CenterRouteRoute,
} as any)
const CenterExamFormsRoute = CenterExamFormsRouteImport.update({
  id: '/exam-forms',
  path: '/exam-forms',
  getParentRoute: () => CenterRouteRoute,
} as any)
const CenterEnrollRoute = CenterEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => CenterRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoordinatorsRoute = AdminCoordinatorsRouteImport.update({
  id: '/coordinators',
  path: '/coordinators',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCentersRoute = AdminCentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/center': typeof CenterRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/enquiry': typeof EnquiryRoute
  '/login': typeof LoginRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/center/enroll': typeof CenterEnrollRoute
  '/center/exam-forms': typeof CenterExamFormsRoute
  '/center/marks-entry': typeof CenterMarksEntryRoute
  '/center/settings': typeof CenterSettingsRoute
  '/center/students': typeof CenterStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/center/': typeof CenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/enquiry': typeof EnquiryRoute
  '/login': typeof LoginRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/center/enroll': typeof CenterEnrollRoute
  '/center/exam-forms': typeof CenterExamFormsRoute
  '/center/marks-entry': typeof CenterMarksEntryRoute
  '/center/settings': typeof CenterSettingsRoute
  '/center/students': typeof CenterStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/center': typeof CenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/center': typeof CenterRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/enquiry': typeof EnquiryRoute
  '/login': typeof LoginRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/center/enroll': typeof CenterEnrollRoute
  '/center/exam-forms': typeof CenterExamFormsRoute
  '/center/marks-entry': typeof CenterMarksEntryRoute
  '/center/settings': typeof CenterSettingsRoute
  '/center/students': typeof CenterStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/center/': typeof CenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/center'
    | '/about'
    | '/enquiry'
    | '/login'
    | '/admin/centers'
    | '/admin/coordinators'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/notices'
    | '/admin/settings'
    | '/center/enroll'
    | '/center/exam-forms'
    | '/center/marks-entry'
    | '/center/settings'
    | '/center/students'
    | '/admin/'
    | '/center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/enquiry'
    | '/login'
    | '/admin/centers'
    | '/admin/coordinators'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/notices'
    | '/admin/settings'
    | '/center/enroll'
    | '/center/exam-forms'
    | '/center/marks-entry'
    | '/center/settings'
    | '/center/students'
    | '/admin'
    | '/center'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/center'
    | '/about'
    | '/enquiry'
    | '/login'
    | '/admin/centers'
    | '/admin/coordinators'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/notices'
    | '/admin/settings'
    | '/center/enroll'
    | '/center/exam-forms'
    | '/center/marks-entry'
    | '/center/settings'
    | '/center/students'
    | '/admin/'
    | '/center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CenterRouteRoute: typeof CenterRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  EnquiryRoute: typeof EnquiryRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/': {
      id: '/center/'
      path: '/'
      fullPath: '/center/'
      preLoaderRoute: typeof CenterIndexRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/center/students': {
      id: '/center/students'
      path: '/students'
      fullPath: '/center/students'
      preLoaderRoute: typeof CenterStudentsRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/center/settings': {
      id: '/center/settings'
      path: '/settings'
      fullPath: '/center/settings'
      preLoaderRoute: typeof CenterSettingsRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/center/marks-entry': {
      id: '/center/marks-entry'
      path: '/marks-entry'
      fullPath: '/center/marks-entry'
      preLoaderRoute: typeof CenterMarksEntryRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/center/exam-forms': {
      id: '/center/exam-forms'
      path: '/exam-forms'
      fullPath: '/center/exam-forms'
      preLoaderRoute: typeof CenterExamFormsRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/center/enroll': {
      id: '/center/enroll'
      path: '/enroll'
      fullPath: '/center/enroll'
      preLoaderRoute: typeof CenterEnrollRouteImport
      parentRoute: typeof CenterRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coordinators': {
      id: '/admin/coordinators'
      path: '/coordinators'
      fullPath: '/admin/coordinators'
      preLoaderRoute: typeof AdminCoordinatorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/centers': {
      id: '/admin/centers'
      path: '/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AdminCentersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCentersRoute: typeof AdminCentersRoute
  AdminCoordinatorsRoute: typeof AdminCoordinatorsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCentersRoute: AdminCentersRoute,
  AdminCoordinatorsRoute: AdminCoordinatorsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CenterRouteRouteChildren {
  CenterEnrollRoute: typeof CenterEnrollRoute
  CenterExamFormsRoute: typeof CenterExamFormsRoute
  CenterMarksEntryRoute: typeof CenterMarksEntryRoute
  CenterSettingsRoute: typeof CenterSettingsRoute
  CenterStudentsRoute: typeof CenterStudentsRoute
  CenterIndexRoute: typeof CenterIndexRoute
}

const CenterRouteRouteChildren: CenterRouteRouteChildren = {
  CenterEnrollRoute: CenterEnrollRoute,
  CenterExamFormsRoute: CenterExamFormsRoute,
  CenterMarksEntryRoute: CenterMarksEntryRoute,
  CenterSettingsRoute: CenterSettingsRoute,
  CenterStudentsRoute: CenterStudentsRoute,
  CenterIndexRoute: CenterIndexRoute,
}

const CenterRouteRouteWithChildren = CenterRouteRoute._addFileChildren(
  CenterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CenterRouteRoute: CenterRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  EnquiryRoute: EnquiryRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
